import type { NetworkType } from "./schema.js";
import { VENDORED_CHAIN_VERSION } from "./vendor-info.js";

/**
 * Per-network-type defaults, deep-merged UNDER user input by withDefaults().
 * Values mirror deploy/config/network/<type>/chain.env and the design §4
 * sample where the chain repo has no opinion.
 */
export interface Profile {
  token: { exponent: number; minGasPrice: string };
  providers: {
    policy: {
      auditedOnly: boolean;
      minUptime7d: number;
      maxPriceMultiplier: number;
      antiAffinity: "strict" | "preferSpread";
    };
    escrow: { targetRunwayDays: number };
  };
  chainParams: Record<string, Record<string, unknown>>;
  images: { sparkdreamd: string; headscale: string; explorer: string; frontend: string };
  security: { keyMode: "softsign" | "tmkms" };
  infra: {
    akashNetwork: "mainnet" | "sandbox";
    resources: {
      validator: RoleResources;
      sentry: RoleResources;
    };
    sentrySettings: {
      pruning: "default" | "nothing" | "everything" | "custom";
      snapshotInterval: number;
      snapshotKeepRecent: number;
      stateSync: boolean;
    };
  };
}

interface RoleResources {
  cpu: number;
  memory: string;
  storage: { root: string; data: string; persistent: boolean; class: "beta1" | "beta2" | "beta3" };
}

// Image defaults track the vendored chain version (vendor-info.ts,
// regenerated by sync-vendor.sh): the vendored reference genesis carries
// params that older binaries reject at InitChain, and validateSpec enforces
// that floor. No mainnet image is published yet: mainnet launches fail fast
// at validate-spec's Docker Hub check until one is pushed.
const SPARKDREAMD_VERSION = {
  devnet: VENDORED_CHAIN_VERSION,
  testnet: VENDORED_CHAIN_VERSION,
  mainnet: VENDORED_CHAIN_VERSION,
};
const HEADSCALE_IMAGE = "sparkdreamnft/headscale:v0.28.0";
// v1.0.6+: renders its chain config from env at runtime (CHAIN_NAME,
// CHAIN_DENOM, ...) — earlier tags serve the config baked at build time
const EXPLORER_IMAGE = "sparkdreamnft/sparkdream-explorer:v1.0.6";
const FRONTEND_IMAGE = "sparkdreamnft/sparkdream-ui:v1.0.48";

const nodeResources = {
  validator: {
    cpu: 1,
    memory: "8Gi",
    storage: { root: "5Gi", data: "50Gi", persistent: true, class: "beta3" as const },
  },
  sentry: {
    cpu: 2,
    memory: "8Gi",
    storage: { root: "5Gi", data: "8Gi", persistent: true, class: "beta3" as const },
  },
};

/**
 * Genesis module parameters (staking, gov, mint, distribution, slashing)
 * carry NO profile defaults: the vendored reference genesis for the network
 * type provides them, and chainParams entries are user overrides on top.
 * Profiles only default what the reference genesis doesn't cover —
 * consensus timing (config.toml) and gentx commission flags.
 */
const commonChainParams = {
  consensus: { timeoutCommit: "3s" },
  validatorDefaults: {
    commissionRate: 0.05,
    commissionMaxRate: 0.2,
    commissionMaxChangeRate: 0.01,
  },
};

export const profiles: Record<NetworkType, Profile> = {
  devnet: {
    token: { exponent: 6, minGasPrice: "0" },
    providers: {
      policy: {
        auditedOnly: false,
        minUptime7d: 0.9,
        maxPriceMultiplier: 3.0,
        antiAffinity: "preferSpread",
      },
      escrow: { targetRunwayDays: 7 },
    },
    chainParams: {
      ...commonChainParams,
      consensus: { timeoutCommit: "1s" },
    },
    images: {
      sparkdreamd: `sparkdreamnft/sparkdreamd-devnet-ssh:${SPARKDREAMD_VERSION.devnet}`,
      headscale: HEADSCALE_IMAGE,
      explorer: EXPLORER_IMAGE,
      frontend: FRONTEND_IMAGE,
    },
    security: { keyMode: "softsign" },
    infra: {
      // mainnet since the ACT migration — deployments pay uact everywhere;
      // the Akash sandbox (uakt) is opt-in via an explicit spec override
      akashNetwork: "mainnet",
      resources: nodeResources,
      sentrySettings: {
        pruning: "default",
        snapshotInterval: 1000,
        snapshotKeepRecent: 2,
        stateSync: false,
      },
    },
  },

  testnet: {
    token: { exponent: 6, minGasPrice: "25000" },
    providers: {
      policy: {
        auditedOnly: true,
        minUptime7d: 0.99,
        maxPriceMultiplier: 2.0,
        antiAffinity: "strict",
      },
      escrow: { targetRunwayDays: 30 },
    },
    chainParams: { ...commonChainParams },
    images: {
      sparkdreamd: `sparkdreamnft/sparkdreamd-testnet-ssh:${SPARKDREAMD_VERSION.testnet}`,
      headscale: HEADSCALE_IMAGE,
      explorer: EXPLORER_IMAGE,
      frontend: FRONTEND_IMAGE,
    },
    security: { keyMode: "softsign" },
    infra: {
      akashNetwork: "mainnet",
      resources: nodeResources,
      sentrySettings: {
        pruning: "default",
        snapshotInterval: 1000,
        snapshotKeepRecent: 2,
        stateSync: false,
      },
    },
  },

  mainnet: {
    token: { exponent: 6, minGasPrice: "25000" },
    providers: {
      policy: {
        auditedOnly: true,
        minUptime7d: 0.99,
        maxPriceMultiplier: 2.0,
        antiAffinity: "strict",
      },
      escrow: { targetRunwayDays: 30 },
    },
    chainParams: { ...commonChainParams },
    images: {
      sparkdreamd: `sparkdreamnft/sparkdreamd-mainnet-ssh:${SPARKDREAMD_VERSION.mainnet}`,
      headscale: HEADSCALE_IMAGE,
      explorer: EXPLORER_IMAGE,
      frontend: FRONTEND_IMAGE,
    },
    security: { keyMode: "tmkms" },
    infra: {
      akashNetwork: "mainnet",
      resources: nodeResources,
      sentrySettings: {
        pruning: "default",
        snapshotInterval: 1000,
        snapshotKeepRecent: 2,
        stateSync: false,
      },
    },
  },
};
