// Generated by scripts: pnpm sync-releases — do not edit by hand.
//
// Known chain releases (§13): version, the chain-repo commit each release's
// deploy data came from, and the published sparkdreamd images with their
// registry manifest digests (when resolvable at sync time). A version
// missing here is UNKNOWN to this launcher build, not invalid — resolution
// escalates to the user. Newest first.
export interface ChainReleaseImage {
  image: string;
  /** Registry manifest digest at sync time — fetch mode verifies against it. */
  digest?: string;
}

export interface ChainRelease {
  version: string;
  /** Chain-repo commit of this release's deploy data (its bump commit). */
  commit: string;
  images: ChainReleaseImage[];
}

export const CHAIN_RELEASES: ChainRelease[] = [
  {
    "version": "v1.0.45",
    "commit": "99784aabe7e521326aa8161131bc43e70ebb0c3c",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.45",
        "digest": "sha256:5e7e7c4cff2764b5ff10894f2f41b8ec3abced2b32f6d85034830865fb197e90"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.45"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.45",
        "digest": "sha256:e36ed898cac3821d591e82e3344a9a07117dd6e28f0dd3ebe0c20ce23ed57f33"
      }
    ]
  },
  {
    "version": "v1.0.44",
    "commit": "b5160ea9cf59d58b447b366f80e5add2b4fa566c",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.44",
        "digest": "sha256:0af021b2a80245ba4aa770da808cbc8ea24cc56f0bb8ebddb436d119b5be062f"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.44"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.44",
        "digest": "sha256:b26c86d34dd796835b874785303528360a683bf7c71ff0a11cff99b7bd2baa68"
      }
    ]
  },
  {
    "version": "v1.0.43",
    "commit": "f5ad46925ccb1a39b1a63db99ec33a4674d6b4ac",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.43",
        "digest": "sha256:e9928b272428906baea0e8d774908d21ce3f7e4f4b97ffddfc388880e6f75860"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.43"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.43",
        "digest": "sha256:64b2773aa9a9ddf2bdf449f21ec89e9bf5e524cee828aaa5aee457613da93205"
      }
    ]
  },
  {
    "version": "v1.0.42",
    "commit": "42742f10ea928eed2d96340102b987b71d1476c7",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.42",
        "digest": "sha256:19981152ae34267f15540529c260a8cae8e31021340be61ffa45712d8b363fa7"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.42"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.42",
        "digest": "sha256:8ee77707f0dbed2d1e0fad1152235ec887bc70bd7402667ad7d7d05c4128bc71"
      }
    ]
  },
  {
    "version": "v1.0.41",
    "commit": "52da21024a4e2321d57613c8fcd578a3a7583e9f",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.41",
        "digest": "sha256:a6a1910ea1e2542579185910d6d1cfde5c158b9f027326df6b1811d70bfdfac3"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.41"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.41",
        "digest": "sha256:ba697d586413d7b6faf235a8c3294b0bd865c58217d206d303012581e7f1e691"
      }
    ]
  },
  {
    "version": "v1.0.40",
    "commit": "d81f3c87d68daf75c5047223735da64f534d2626",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.40",
        "digest": "sha256:58d94683a85f0024aed931c94ed04909e13849a7a9821cd6f08333be8c43952a"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.40"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.40",
        "digest": "sha256:2d8eddc453323825e64461b07a9d250ae2f19eddb37ff7c9384275ded45e20ff"
      }
    ]
  },
  {
    "version": "v1.0.39",
    "commit": "7b404028a74a2145260d296db1df31796138aa62",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.39",
        "digest": "sha256:e3cda6a1b8f0660f56bb0cc922d04ef78e31782a1316aec46cc97849c4456d67"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.39"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.39",
        "digest": "sha256:556b1957f0c7e0f145072bec8b54094a030c97bdbd391180caca0b40b778881c"
      }
    ]
  },
  {
    "version": "v1.0.38",
    "commit": "f5af7eae581c74e78d20f8e886a05fec0aacaf42",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.38",
        "digest": "sha256:8ff350aff2e774614fcac2ff87bfe974e5ad71e61290e3295afad06e1599101e"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.38"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.38",
        "digest": "sha256:1927254448eb579d4e81da5aa848aadcc3fbb17c2049240d92fa6796406da3cc"
      }
    ]
  },
  {
    "version": "v1.0.37",
    "commit": "da4b3a567d089a2ef6fd6ab82627e6d1f845e6ad",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.37",
        "digest": "sha256:566fd63935f860d09775aa8b308da1d5fa378d1de69fd9421dd5eb6c21dd06e1"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.37"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.37",
        "digest": "sha256:eaab35f7ad5471cf4ccac9488ca43b818b45a7961cf118285bbbcaf713fcc433"
      }
    ]
  },
  {
    "version": "v1.0.36",
    "commit": "c954ee4afbcee6654cad5a96cd90dae5d442afb8",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.36",
        "digest": "sha256:b42012255b6ebb73a73a3114fd6ad35684a0130efb8d7ce255346a91250e2810"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.36"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.36",
        "digest": "sha256:ccfc545d7a2bf5f602f9e7f19d25f9c73da26fd047521e64677435d57928250a"
      }
    ]
  },
  {
    "version": "v1.0.35",
    "commit": "67ec08873096bc9344df6edace1e2a8c83be3009",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.35",
        "digest": "sha256:25b4c5b52889e58492f454d9ccf6f33ea1a2526bcc99ff6f2012576da11f00cf"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.35"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.35",
        "digest": "sha256:18c5056f8d4cea32075800879d8a19ded6c347f17fc07f4aff4cbacd5753a7c6"
      }
    ]
  },
  {
    "version": "v1.0.34",
    "commit": "f084b1fe98cb465f8bc8e181f3e360a32f86c510",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.34",
        "digest": "sha256:10b5d8a9cf885bef43dbd58d8ffc3aca32d38aa102fe9c1a451a32324df2a4a7"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.34"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.34",
        "digest": "sha256:77a96918fef5268a71ff21b6ea6fe83386ae78a070a9be81e0b056797029a7e3"
      }
    ]
  },
  {
    "version": "v1.0.33",
    "commit": "c0e45c5fee0144a4170789871c28d9502b790b88",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.33",
        "digest": "sha256:d8249115a01f49b48517570cb5dac36aec59dfb2078dede46aadc9d471b05721"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.33"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.33",
        "digest": "sha256:ac780cc55f55cb8ebdaa6c3b1944eaa50687a34ec25278b801ef9ec087e778bf"
      }
    ]
  },
  {
    "version": "v1.0.32",
    "commit": "4dd51c1f71158976f55b010fec51dc46a054d9ff",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.32",
        "digest": "sha256:9d6f61088fde7fbf6f6c7850b62a2898d2ff227c35768d926590f7ec41c39806"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.32"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.32",
        "digest": "sha256:11ceb7fa57a1afadb8157ddd0988bf4cdc071fbe720f9173a4a36dd6b47d7967"
      }
    ]
  },
  {
    "version": "v1.0.31",
    "commit": "cfede151cb0c27cb88d24376084bbb32ca71fc6e",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.31",
        "digest": "sha256:7071b9c0dc03e1ee3b4ffc4097bf78d48c27d369dae43b25f5b86e430ba943ea"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.31"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.31",
        "digest": "sha256:015ae2a1aa9a9044d1479b0a5f8410f84ff35bd0a679d57bcdc5aaa1fe70bd77"
      }
    ]
  },
  {
    "version": "v1.0.30",
    "commit": "3f7ec34631824b3c378b1b13f1563595c16ca3d3",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.30",
        "digest": "sha256:2b4db850d98aa341d0459993633f893520ea2fc85a27daae6dbdbc0112aab0f4"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.30"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.30",
        "digest": "sha256:e52ce378abb66781cf13eaa67dfe68ae02a31574ad5799a0801057bc9aaafb17"
      }
    ]
  },
  {
    "version": "v1.0.29",
    "commit": "6ebeda2e87b7fad8ae01126d613bfdf2a59bea12",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.29",
        "digest": "sha256:66a006effdd84e0abcb8adcbd5e4948f1b1ffe41a8f71d604f511bf49a1e7ff3"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.29"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.29",
        "digest": "sha256:8885dbc0a69c122bc9d16693da14e9aabe25fccd7ca3b13685701e9a46631caf"
      }
    ]
  },
  {
    "version": "v1.0.28",
    "commit": "39b83eebaf759c084ae55eeed08a894451a924eb",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.28",
        "digest": "sha256:0a4b8105e2057cc99cde19f7030e5d13a3ac55f4279f8f977420e69501307d82"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.28"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.28",
        "digest": "sha256:38e4e40d276a08d160803c5667d3b3e68ae9d04d9829b0b262f9663889a6caf1"
      }
    ]
  },
  {
    "version": "v1.0.27",
    "commit": "231369a93fcc57fead3884b28e2b07f77e79c26c",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.27",
        "digest": "sha256:c2a8f1ea812026bb49a062b250180e0be3a34d5996a24268b57d74e36f6814b3"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.27"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.27",
        "digest": "sha256:9b9e23870d2cf3849eb8070fa80742f89df32cb9a01a48c551a25904788ffb51"
      }
    ]
  },
  {
    "version": "v1.0.26",
    "commit": "c8e001433d833339b3ea6378d57930eede7777ab",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.26",
        "digest": "sha256:a0fd58169d825f5b0375f0456f4d3e6809f65b199bc77d4084fb133421e44bfd"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.26"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.26",
        "digest": "sha256:95c101fc213ddefa51b0e852f850214722c9d00f6e26d365f37653a645c9a729"
      }
    ]
  },
  {
    "version": "v1.0.25",
    "commit": "1018b604f466423b915576f35761ec136aaff47d",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.25",
        "digest": "sha256:22bd3b7b01286b65baeb888c5402a04751c0158406185369df4f70dac07e414a"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.25"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.25"
      }
    ]
  },
  {
    "version": "v1.0.24",
    "commit": "68ad90d5284e212041313693b2a18505cd86b2f1",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.24",
        "digest": "sha256:8ec2e2bb7b81ce7494c275ce4ca130d23c983d7e13ffcf3eec641b57538f9ecb"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.24"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.24",
        "digest": "sha256:383887c80362d53caa1bb54a3937a865d836033602202b4a7a8355c9da560bf8"
      }
    ]
  },
  {
    "version": "v1.0.23",
    "commit": "da1c7fb087b9f0270f55f35448b1205c7f392643",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.23"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.23"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.23",
        "digest": "sha256:214e598af96a28bb13ede958f4b166491cc282d88e7a7d4af8f8d8267b6fb534"
      }
    ]
  },
  {
    "version": "v1.0.22",
    "commit": "3edf0c0cb7273979bd7df834b8995c002cd4f2b7",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.22"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.22"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.22",
        "digest": "sha256:a9c44192b15ba2e0fa948fc844e99b7f4262547a94b17dcafbc465bd8021a483"
      }
    ]
  },
  {
    "version": "v1.0.21",
    "commit": "c87d94f812b92c5df68dd096144ec97812ad7e35",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.21"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.21"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.21",
        "digest": "sha256:7e10df02a2cc67242119d60679f8a650eea8f76d5fa09393ad2995c5f6c12dbd"
      }
    ]
  },
  {
    "version": "v1.0.20",
    "commit": "7d77a070cb1d0ac3b2319a0007f3102d17e0ca7e",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.20"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.20"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.20",
        "digest": "sha256:2bce10e34c7312ae97b27a1d7d9212869a35cebe09057efd3cba7b617bcbf5e2"
      }
    ]
  },
  {
    "version": "v1.0.19",
    "commit": "21bc8a60d08175b41dbb8a1251fff9b7fa51ac84",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.19"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.19"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.19",
        "digest": "sha256:de7c6287481f403c37b29157f9289d80f6316ef8f1c95f03c99f235e377f7c44"
      }
    ]
  },
  {
    "version": "v1.0.18",
    "commit": "50ac7efb5a45d3058a2122cfb391b7b071bb74b2",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.18"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.18"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.18",
        "digest": "sha256:15875fb29bf7b2a0ff7deee76429af9c12bfd1648ce1f57ae69afeb8264c2727"
      }
    ]
  },
  {
    "version": "v1.0.17",
    "commit": "afda96b7a58a357e5fb50ea7fe9879f4ed757d8b",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.17"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.17"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.17",
        "digest": "sha256:0e7b82c9cc1a7116ad3538c93f1a5e6fb30a207b5f99baff71fbdc58565fba30"
      }
    ]
  },
  {
    "version": "v1.0.16",
    "commit": "78ebc754751de9a4b7488461954d3171ec640906",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.16"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.16"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.16",
        "digest": "sha256:b1db447923cfc0cf3468aa27f2b6cb4a1c67716dc62a61958ef832ed4ffeb75f"
      }
    ]
  },
  {
    "version": "v1.0.15",
    "commit": "eebff99edd0a79a2ee4988b8a95fbef0a8ae12c1",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.15"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.15"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.15",
        "digest": "sha256:cf10e0e2eac66b6615e24235e53db8a231c0dbd89db90b2dde2ffa332dee5e4a"
      }
    ]
  },
  {
    "version": "v1.0.14",
    "commit": "3a7b520ff2a22af377559ef70fe16b1323ccf1bb",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.14"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.14"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.14",
        "digest": "sha256:6ca68d7a7a40ceebfe83682ce5eee8b97ac6553dbc57ced3759c49f8549b3e1e"
      }
    ]
  },
  {
    "version": "v1.0.13",
    "commit": "d1ae6583efa27ce58bbb2846360b728fbe2c0bb1",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.13"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.13"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.13",
        "digest": "sha256:002fce8dbada2adcfba99243621f6000d791634a4b15e29db5188f3c6219c6fb"
      }
    ]
  },
  {
    "version": "v1.0.12",
    "commit": "e15faebfb3a7c77f019ba82ac6876865c3f1d58f",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.12"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.12"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.12",
        "digest": "sha256:d9abda3a38b35e6d67b5efcfef593ed67e1dbdf4e4799e3db4072eb24634800c"
      }
    ]
  },
  {
    "version": "v1.0.11",
    "commit": "4971c5dfa9a9278a208577c50c87294d4885cb81",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.11"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.11"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.11",
        "digest": "sha256:0391e290aba95cb0ed119ffe27ed08010f6bebee45fefc7e47bf36c0979f58d0"
      }
    ]
  },
  {
    "version": "v1.0.10",
    "commit": "5f671a9cffa50f4d48340740fca8327ae3f59d59",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.10"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.10"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.10",
        "digest": "sha256:a273dd4e8275789186e036b63b3963e293039ca9d5c2e738d471c56e6b2f1a1c"
      }
    ]
  },
  {
    "version": "v1.0.9",
    "commit": "976d9a9c8034f35c3bc7f7adaa58bf5b2ede04b4",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.9"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.9"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.9",
        "digest": "sha256:1a7c2c5ee9c15518b04e6791d826a5c49c986fa877b73d6163efddeb11413b1e"
      }
    ]
  },
  {
    "version": "v1.0.8",
    "commit": "c91d27304bc3ff7fcbcbf0a00b7d718cb57e44dc",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.8"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.8"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.8",
        "digest": "sha256:2d44034fb65fc2dcc491a74ef13a4371979dbb09084f213577b2d39378219cdc"
      }
    ]
  },
  {
    "version": "v1.0.7",
    "commit": "7d466c19a8022ba83b4bfc5820e70722b9d4e180",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.7"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.7"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.7",
        "digest": "sha256:80a556fe92d81c8169d0923e720a0d7f137a6c7286c1df6ed6f3ca13b7c9be24"
      }
    ]
  },
  {
    "version": "v1.0.6",
    "commit": "909ddf7d0fc51390ab6b97cc70f1a80ca819285d",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.6"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.6"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.6",
        "digest": "sha256:b1350dace65346ee7fbf503c96611aa348cea239d7aee922e166411c8f721acf"
      }
    ]
  },
  {
    "version": "v1.0.5",
    "commit": "ea6ff66a671f795f4ab41774e3d3ec653180ae77",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.5"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.5"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.5",
        "digest": "sha256:efe3bfcdf33e5b8e5375c6d87c89f16a16b4ddd7c928b02691448e8505591e71"
      }
    ]
  },
  {
    "version": "v1.0.4",
    "commit": "328e357307dfbe9c7273e01f613651a60af2576b",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.4"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.4"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.4",
        "digest": "sha256:1e1a07e1a268c304d3cccf4655e6b47dd56b7f7d39d4dba9dc102505d11c645f"
      }
    ]
  },
  {
    "version": "v1.0.3",
    "commit": "81c27418ccc44e0a804d29ba97d410c9b827514f",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.3",
        "digest": "sha256:a0ef43f1eccb2d377c8ed9b8c656ce7617c7878b66743427f8a3efcaeebb0d06"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.3"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.3",
        "digest": "sha256:b1f8d559bf2434ea6edc1f6fa2753cbf9df34e66611f233ec1e12d51113f9f0f"
      }
    ]
  },
  {
    "version": "v1.0.2",
    "commit": "8ef40d684c6c5229e8a5e9130bb82c760c36be54",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.2",
        "digest": "sha256:aedcd9e2883733d1e373c622ddff6a6442dfd1be6a7f87e5db19f56207016734"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.2"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.2",
        "digest": "sha256:1c36cf812f007c2edafe893fda61168cbd500844c2b0f835f36cf752c3b3e4f4"
      }
    ]
  },
  {
    "version": "v1.0.1",
    "commit": "c71b1e7786847bcdd7bfdabafdf4de9a12a95b5a",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.1e",
        "digest": "sha256:92968b0ca4109ef97dd7412d6f5d17178ac4c7279136085ffabe24fe53dcaa4c"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.1e"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.1e"
      }
    ]
  },
  {
    "version": "v1.0.0",
    "commit": "325b0b63e3631614d7e013bbb02a7fde0bb84dfc",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.0",
        "digest": "sha256:3d39b1998652db1771a70437089f0962d5f38d0fb4edc5ed91b09566eb8559af"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.0"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.0"
      }
    ]
  }
];
