// Generated by scripts: pnpm sync-releases — do not edit by hand.
//
// Known chain releases (§13): version, the chain-repo commit each release's
// deploy data came from, and the published sparkdreamd images with their
// registry manifest digests (when resolvable at sync time). A version
// missing here is UNKNOWN to this launcher build, not invalid — resolution
// escalates to the user. Newest first.
export interface ChainReleaseImage {
  image: string;
  /** Registry manifest digest at sync time — fetch mode verifies against it. */
  digest?: string;
}

export interface ChainRelease {
  version: string;
  /** Chain-repo commit of this release's deploy data (its bump commit). */
  commit: string;
  images: ChainReleaseImage[];
}

export const CHAIN_RELEASES: ChainRelease[] = [
  {
    "version": "v1.0.26",
    "commit": "c8e001433d833339b3ea6378d57930eede7777ab",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.26",
        "digest": "sha256:a0fd58169d825f5b0375f0456f4d3e6809f65b199bc77d4084fb133421e44bfd"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.26"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.26",
        "digest": "sha256:95c101fc213ddefa51b0e852f850214722c9d00f6e26d365f37653a645c9a729"
      }
    ]
  },
  {
    "version": "v1.0.25",
    "commit": "1018b604f466423b915576f35761ec136aaff47d",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.25",
        "digest": "sha256:22bd3b7b01286b65baeb888c5402a04751c0158406185369df4f70dac07e414a"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.25"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.25"
      }
    ]
  },
  {
    "version": "v1.0.24",
    "commit": "68ad90d5284e212041313693b2a18505cd86b2f1",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.24",
        "digest": "sha256:8ec2e2bb7b81ce7494c275ce4ca130d23c983d7e13ffcf3eec641b57538f9ecb"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.24"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.24",
        "digest": "sha256:383887c80362d53caa1bb54a3937a865d836033602202b4a7a8355c9da560bf8"
      }
    ]
  },
  {
    "version": "v1.0.23",
    "commit": "da1c7fb087b9f0270f55f35448b1205c7f392643",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.23"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.23"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.23",
        "digest": "sha256:214e598af96a28bb13ede958f4b166491cc282d88e7a7d4af8f8d8267b6fb534"
      }
    ]
  },
  {
    "version": "v1.0.22",
    "commit": "3edf0c0cb7273979bd7df834b8995c002cd4f2b7",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.22"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.22"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.22",
        "digest": "sha256:a9c44192b15ba2e0fa948fc844e99b7f4262547a94b17dcafbc465bd8021a483"
      }
    ]
  },
  {
    "version": "v1.0.21",
    "commit": "c87d94f812b92c5df68dd096144ec97812ad7e35",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.21"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.21"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.21",
        "digest": "sha256:7e10df02a2cc67242119d60679f8a650eea8f76d5fa09393ad2995c5f6c12dbd"
      }
    ]
  },
  {
    "version": "v1.0.20",
    "commit": "7d77a070cb1d0ac3b2319a0007f3102d17e0ca7e",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.20"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.20"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.20",
        "digest": "sha256:2bce10e34c7312ae97b27a1d7d9212869a35cebe09057efd3cba7b617bcbf5e2"
      }
    ]
  },
  {
    "version": "v1.0.19",
    "commit": "21bc8a60d08175b41dbb8a1251fff9b7fa51ac84",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.19"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.19"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.19",
        "digest": "sha256:de7c6287481f403c37b29157f9289d80f6316ef8f1c95f03c99f235e377f7c44"
      }
    ]
  },
  {
    "version": "v1.0.18",
    "commit": "50ac7efb5a45d3058a2122cfb391b7b071bb74b2",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.18"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.18"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.18",
        "digest": "sha256:15875fb29bf7b2a0ff7deee76429af9c12bfd1648ce1f57ae69afeb8264c2727"
      }
    ]
  },
  {
    "version": "v1.0.17",
    "commit": "afda96b7a58a357e5fb50ea7fe9879f4ed757d8b",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.17"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.17"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.17",
        "digest": "sha256:0e7b82c9cc1a7116ad3538c93f1a5e6fb30a207b5f99baff71fbdc58565fba30"
      }
    ]
  },
  {
    "version": "v1.0.16",
    "commit": "78ebc754751de9a4b7488461954d3171ec640906",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.16"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.16"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.16",
        "digest": "sha256:b1db447923cfc0cf3468aa27f2b6cb4a1c67716dc62a61958ef832ed4ffeb75f"
      }
    ]
  },
  {
    "version": "v1.0.15",
    "commit": "eebff99edd0a79a2ee4988b8a95fbef0a8ae12c1",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.15"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.15"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.15",
        "digest": "sha256:cf10e0e2eac66b6615e24235e53db8a231c0dbd89db90b2dde2ffa332dee5e4a"
      }
    ]
  },
  {
    "version": "v1.0.14",
    "commit": "3a7b520ff2a22af377559ef70fe16b1323ccf1bb",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.14"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.14"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.14",
        "digest": "sha256:6ca68d7a7a40ceebfe83682ce5eee8b97ac6553dbc57ced3759c49f8549b3e1e"
      }
    ]
  },
  {
    "version": "v1.0.13",
    "commit": "d1ae6583efa27ce58bbb2846360b728fbe2c0bb1",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.13"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.13"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.13",
        "digest": "sha256:002fce8dbada2adcfba99243621f6000d791634a4b15e29db5188f3c6219c6fb"
      }
    ]
  },
  {
    "version": "v1.0.12",
    "commit": "e15faebfb3a7c77f019ba82ac6876865c3f1d58f",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.12"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.12"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.12",
        "digest": "sha256:d9abda3a38b35e6d67b5efcfef593ed67e1dbdf4e4799e3db4072eb24634800c"
      }
    ]
  },
  {
    "version": "v1.0.11",
    "commit": "4971c5dfa9a9278a208577c50c87294d4885cb81",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.11"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.11"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.11",
        "digest": "sha256:0391e290aba95cb0ed119ffe27ed08010f6bebee45fefc7e47bf36c0979f58d0"
      }
    ]
  },
  {
    "version": "v1.0.10",
    "commit": "5f671a9cffa50f4d48340740fca8327ae3f59d59",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.10"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.10"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.10",
        "digest": "sha256:a273dd4e8275789186e036b63b3963e293039ca9d5c2e738d471c56e6b2f1a1c"
      }
    ]
  },
  {
    "version": "v1.0.9",
    "commit": "976d9a9c8034f35c3bc7f7adaa58bf5b2ede04b4",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.9"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.9"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.9",
        "digest": "sha256:1a7c2c5ee9c15518b04e6791d826a5c49c986fa877b73d6163efddeb11413b1e"
      }
    ]
  },
  {
    "version": "v1.0.8",
    "commit": "c91d27304bc3ff7fcbcbf0a00b7d718cb57e44dc",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.8"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.8"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.8",
        "digest": "sha256:2d44034fb65fc2dcc491a74ef13a4371979dbb09084f213577b2d39378219cdc"
      }
    ]
  },
  {
    "version": "v1.0.7",
    "commit": "7d466c19a8022ba83b4bfc5820e70722b9d4e180",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.7"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.7"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.7",
        "digest": "sha256:80a556fe92d81c8169d0923e720a0d7f137a6c7286c1df6ed6f3ca13b7c9be24"
      }
    ]
  },
  {
    "version": "v1.0.6",
    "commit": "909ddf7d0fc51390ab6b97cc70f1a80ca819285d",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.6"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.6"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.6",
        "digest": "sha256:b1350dace65346ee7fbf503c96611aa348cea239d7aee922e166411c8f721acf"
      }
    ]
  },
  {
    "version": "v1.0.5",
    "commit": "ea6ff66a671f795f4ab41774e3d3ec653180ae77",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.5"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.5"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.5",
        "digest": "sha256:efe3bfcdf33e5b8e5375c6d87c89f16a16b4ddd7c928b02691448e8505591e71"
      }
    ]
  },
  {
    "version": "v1.0.4",
    "commit": "328e357307dfbe9c7273e01f613651a60af2576b",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.4"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.4"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.4",
        "digest": "sha256:1e1a07e1a268c304d3cccf4655e6b47dd56b7f7d39d4dba9dc102505d11c645f"
      }
    ]
  },
  {
    "version": "v1.0.3",
    "commit": "81c27418ccc44e0a804d29ba97d410c9b827514f",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.3",
        "digest": "sha256:a0ef43f1eccb2d377c8ed9b8c656ce7617c7878b66743427f8a3efcaeebb0d06"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.3"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.3",
        "digest": "sha256:b1f8d559bf2434ea6edc1f6fa2753cbf9df34e66611f233ec1e12d51113f9f0f"
      }
    ]
  },
  {
    "version": "v1.0.2",
    "commit": "8ef40d684c6c5229e8a5e9130bb82c760c36be54",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.2",
        "digest": "sha256:aedcd9e2883733d1e373c622ddff6a6442dfd1be6a7f87e5db19f56207016734"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.2"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.2",
        "digest": "sha256:1c36cf812f007c2edafe893fda61168cbd500844c2b0f835f36cf752c3b3e4f4"
      }
    ]
  },
  {
    "version": "v1.0.1",
    "commit": "c71b1e7786847bcdd7bfdabafdf4de9a12a95b5a",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.1e",
        "digest": "sha256:92968b0ca4109ef97dd7412d6f5d17178ac4c7279136085ffabe24fe53dcaa4c"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.1e"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.1e"
      }
    ]
  },
  {
    "version": "v1.0.0",
    "commit": "325b0b63e3631614d7e013bbb02a7fde0bb84dfc",
    "images": [
      {
        "image": "sparkdreamnft/sparkdreamd-devnet-ssh:v1.0.0",
        "digest": "sha256:3d39b1998652db1771a70437089f0962d5f38d0fb4edc5ed91b09566eb8559af"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-mainnet-ssh:v1.0.0"
      },
      {
        "image": "sparkdreamnft/sparkdreamd-testnet-ssh:v1.0.0"
      }
    ]
  }
];
