// Generated by scripts/sync-vendor.sh — do not edit by hand.
//
// The chain version whose deploy data (reference genesis, config templates,
// SDLs) is vendored into vendor/sparkdream-deploy. Profile image defaults and
// validateSpec's minimum-image floor derive from it: binaries older than the
// vendored genesis regeneration reject its params at InitChain.
export const VENDORED_CHAIN_VERSION = "v1.0.33";

/** Chain repo commit the vendor sync was taken from. */
export const VENDORED_CHAIN_COMMIT = "c0e45c5fee0144a4170789871c28d9502b790b88";
