#!/usr/bin/env bash
# Sync deploy templates and SDLs from the chain repo into vendor/.
# Usage: scripts/sync-vendor.sh [path-to-chain-repo]
set -euo pipefail

CHAIN_REPO="${1:-${SPARKDREAM_CHAIN_REPO:-$HOME/cosmos/sparkdream/sparkdream}}"
SRC="$CHAIN_REPO/deploy/config"
MESH="$CHAIN_REPO/deploy/mesh"
DEST="$(cd "$(dirname "$0")/.." && pwd)/vendor/sparkdream-deploy"

if [ ! -d "$SRC/template" ]; then
  echo "error: $SRC/template not found — pass the chain repo path" >&2
  exit 1
fi

mkdir -p "$DEST"
rsync -a --delete \
  --include='template/***' \
  --include='network/' \
  --include='network/*/' \
  --include='network/*/chain.env' \
  --include='network/*/genesis.json' \
  --include='network/*/*.sdl.yaml' \
  --exclude='*' \
  "$SRC/" "$DEST/"
rsync -a --delete \
  --include='*.yaml' --include='*.yml' --include='*.sh' \
  --exclude='*' \
  "$MESH/" "$DEST/mesh/"
# The relayer's scripts: the launcher uploads its own copy of these before
# running them, so a fix reaches a relayer still on an older hermes image
# (2026-10-08: the image's bringup reused a pre-reset chain's client)
mkdir -p "$DEST/hermes"
rsync -a --delete \
  --include='*.sh' \
  --exclude='*' \
  "$CHAIN_REPO/deploy/docker/hermes/" "$DEST/hermes/"

COMMIT="$(git -C "$CHAIN_REPO" rev-parse HEAD 2>/dev/null || echo unknown)"

# The recorded commit is the only provenance the vendored data carries, and
# it is what VENDORED_CHAIN_COMMIT reports to anyone debugging a launch. A
# dirty chain repo makes it a lie: the files copied above are the working
# tree, not that commit. Refuse rather than record something untrue --
# SYNC_VENDOR_ALLOW_DIRTY=1 marks it "-dirty" instead, for iterating on chain
# changes before they are committed.
if [ "$COMMIT" != "unknown" ] && ! git -C "$CHAIN_REPO" diff --quiet HEAD -- deploy/config deploy/mesh deploy/docker/hermes; then
  if [ "${SYNC_VENDOR_ALLOW_DIRTY:-0}" = "1" ]; then
    COMMIT="$COMMIT-dirty"
    echo "warning: chain repo has uncommitted deploy changes; recording $COMMIT" >&2
  else
    echo "error: $CHAIN_REPO has uncommitted changes under deploy/config, deploy/mesh or deploy/docker/hermes." >&2
    echo "       Vendoring now would record commit $COMMIT for files that are not in it." >&2
    echo "       Commit the chain repo first, or re-run with SYNC_VENDOR_ALLOW_DIRTY=1." >&2
    exit 1
  fi
fi

{
  echo "# Synced from the SparkDream chain repo — do not edit by hand."
  echo "# Source: deploy/config in the chain repo"
  echo "# Commit: $COMMIT"
} > "$DEST/SYNC_INFO"

# The chain version whose deploy data we just vendored, read from the data
# itself (the reference SDLs name the chain image). Profile image defaults
# and validateSpec's minimum-image floor derive from the generated file.
CHAIN_VERSION="$(sed -n 's|.*image: *sparkdreamnft/sparkdreamd-[a-z]*-ssh:\(v[0-9][0-9.]*\).*|\1|p' \
  "$DEST/network/testnet/validator.sdl.yaml" | head -1)"
if [ -z "$CHAIN_VERSION" ]; then
  echo "error: could not read the chain image version from network/testnet/validator.sdl.yaml" >&2
  exit 1
fi

VENDOR_INFO="$(cd "$(dirname "$0")/.." && pwd)/packages/launch-spec/src/vendor-info.ts"
cat > "$VENDOR_INFO" <<EOF
// Generated by scripts/sync-vendor.sh — do not edit by hand.
//
// The chain version whose deploy data (reference genesis, config templates,
// SDLs) is vendored into vendor/sparkdream-deploy. Profile image defaults and
// validateSpec's minimum-image floor derive from it: binaries older than the
// vendored genesis regeneration reject its params at InitChain.
export const VENDORED_CHAIN_VERSION = "$CHAIN_VERSION";

/** Chain repo commit the vendor sync was taken from. */
export const VENDORED_CHAIN_COMMIT = "$COMMIT";
EOF

echo "vendored into $DEST (chain version $CHAIN_VERSION):"
find "$DEST" -type f | sort
echo "regenerated $VENDOR_INFO"
